### PR TITLE
append changelog to fulfill the license obligation

### PR DESCRIPTION
**Pull request by SilverSteven**
### Missing notice for modifications on original work (violation of [APACHE-2.0](https://opensource.org/licenses/Apache-2.0))

[**Modification terms and conditions in license**] The original work should be honored while the modifications on it should be attached with prominent notices as the license [APACHE-2.0](https://opensource.org/licenses/Apache-2.0) dictates. Your project is a forking project from [chanjarster/weixin-java-tools](https://github.com/chanjarster/weixin-java-tools) which adopts [APACHE-2.0](https://opensource.org/licenses/Apache-2.0) as its project license. The modification terms and conditions of [APACHE-2.0](https://opensource.org/licenses/Apache-2.0) dictate that:

>[APACHE-2.0](https://opensource.org/licenses/Apache-2.0):
>
>*... You must cause any modified files to carry prominent notices stating that You changed the files ...*

Therefore, I think the project is obligated to abide by the modification terms and conditions in [APACHE-2.0](https://opensource.org/licenses/Apache-2.0).

[**Violation of modification terms and conditions**] I run through your history, and it turns out that you have conducted modifications to the *source files* of original work while didn't provide prominent notices. You have **17** commits which conduct modifications to the original work, all of which are not declared in [README.md](https://github.com/Wechat-Group/WxJava/blob/develop/README.md). Specifically, of the **17** commits, **all** commits are not announced in the file. According to the license terms and conditions above, it is regarded as license violation. Thus, to avoid potential legal risks, I would suggest you carry out prominent notices for the **17** commits. 

[**Fix**] For your convenience, I created a PR with by picking up modification-related commit messages. It adds a few lines in [changelog](https://github.com/xiayingfeng/WxJava/blob/fulfill-license-obligation/changelog) without touching the codebase. Please be comfortable to check it out. 

Full details of the report you could refer to the [html](https://htmlpreview.github.io/?https://github.com/xiayingfeng/WxJava/blob/develop/page.html) file attached. Hope it helps!

Cheers!

### CODE REVIEW

**Comment by binarywang** [comment]
麻烦用中文再解释下吗？不是很理解你的英语所要表达的内容

**Comment by SilverSteven** [comment]
@binarywang 您好，因为本项目fork了[chanjarster/weixin-java-tools](https://github.com/chanjarster/weixin-java-tools)，该项目所使用的license是Apache-2.0。

Apache-2.0 有一个条款对文件的修改做了一些约束，它要求基于受保护项目的再开发或修改，需要在被修改的文件中提供显著的通知（prominent notice）来声明对该文件所做的修改。通过我们对许可证的调研与开源组织的沟通，我们的结论是，严格履行license的修改条款有助于规避相关法律风险。

对本项目，我们也做了检测，发现存在一部分commit修改，没有注明 prominent notice。因此我们提供了两种建议：

1. 摘取相关的commit message放到changelog文件中，然后将changelog置于项目根目录下。这种方式我们已生成，并通过PR申请合并。

2. 在根目录下放置MODIFICATIONS.md或CHANGELOG.md文件，声明"In compliance with the Apache 2.0 license: I declare that this version of the program contains my modifications, which can be seen through the usual "git" mechanism"(根据Apache 2.0许可证：我声明此版本的程序包含我的修改，可以通过“git”机制查看)

**Comment by binarywang** [comment]
> @binarywang 您好，因为本项目fork了[chanjarster/weixin-java-tools](https://github.com/chanjarster/weixin-java-tools)，该项目所使用的license是Apache-2.0。
> 
> Apache-2.0 有一个条款对文件的修改做了一些约束，它要求基于受保护项目的再开发或修改，需要在被修改的文件中提供显著的通知（prominent notice）来声明对该文件所做的修改。通过我们对许可证的调研与开源组织的沟通，我们的结论是，严格履行license的修改条款有助于规避相关法律风险。
> 
> 对本项目，我们也做了检测，发现存在一部分commit修改，没有注明 prominent notice。因此我们提供了两种建议：
> 
> 1. 摘取相关的commit message放到changelog文件中，然后将changelog置于项目根目录下。这种方式我们已生成，并通过PR申请合并。
> 2. 在根目录下放置MODIFICATIONS.md或CHANGELOG.md文件，声明"In compliance with the Apache 2.0 license: I declare that this version of the program contains my modifications, which can be seen through the usual "git" mechanism"(根据Apache 2.0许可证：我声明此版本的程序包含我的修改，可以通过“git”机制查看)

感谢，那是不是你的第二种方式更为简单呢

**Comment by SilverSteven** [comment]
是的，第二种方式更为简单，建议您在后续自行向项目中添加对应文件及陈述，再见。

**Pull request closed without merging**
